### ISSUE TITLE
.identify() doesn't work when adding new property

### ISSUE THREAD

**Issue by kenyeung128** [smartlook/smartlook-client#13] opened 2020-09-21 05:22 UTC
hi

when calling .identify() again with new property, the new property doesn't added into smartlook.

e.g. 

1st time

		smartlookClient.identify(12345, {
			name: 'John Doe',
			email: 'email@domain.com',
			// other custom properties
		})

2nd time

		smartlookClient.identify(12345, {
			domain: 'test.com'
		})

domain: 'test.com' is not added to the smartlook and cannot see. what should we do?

**Comment by amertak** [comment] 2020-09-21 06:51
Hi,
we will look into it.

Will let you know as soon as possible.

**Comment by amertak** [comment] 2020-09-21 08:18
We tried to reproduce your issue, but it is working fine as intended. All 3 properties (email, name, domain) were present in the visitor detail.

Here is the screen, where you can see all the 3 properties.

![image](https://user-images.githubusercontent.com/2790687/93745358-eae0c080-fbe2-11ea-8f43-74eee70b11b9.png)

Could you share more details maybe?

**Comment by kenyeung128** [comment] 2020-09-21 09:34
Does it need to wait for some minutes before it shows up?

it showed up after 1 hour in our case

**Comment by amertak** [comment] 2020-09-21 09:35
Our backend team is looking into it. There might me some edge case issue.

Will let you know later. Thanks for understanding.

**Comment by martinjrk** [comment] 2020-09-22 08:33
> Does it need to wait for some minutes before it shows up? it showed up after 1 hour in our case

Hi @kenyeung128, there are two cases:
1. new user with the first session - changes from identify() show up in the dashboard immediately. User data are saved in temporary DB with current data.
2. same user return after a while - changes from identify() show up in the dashboard after a session is closed. User data are loaded from long term DB where are old data and are updated after the session is closed (up to one hour, usually few minutes)

No data are lost just update takes a long time. However, we are working on the improvement where the data in the dashboard will always be up to date.

**Comment by kenyeung128** [comment] 2020-09-22 08:35
ok thanks.

**Comment by amertak** [comment] 2020-10-22 07:07
Fix is released. Closing

**Closed by amertak** 2020-10-22 07:07 UTC
